### ISSUE TITLE
log-courier gets stuck sometimes when using syslog logging

### ISSUE THREAD

**Issue by sysmonk** [driskell/log-courier#90] opened 2015-01-15 15:06 UTC
Hi,

I've noticed that one of my log-courier gets constantly stuck, but i don't know why..
After i start log-courier, it works for some random amount of time ( can be 2 seconds, can be a few hours) and then it gets stuck. Example:

```
Jan 15 15:02:01 smtp1 log-courier[26473]: ACKN message received for payload 22336bf0fc38f86dad38058d67ef5831 sequence 128
Jan 15 15:02:01 smtp1 log-courier[26473]: 2 payloads still pending, resetting timeout
Jan 15 15:02:01 smtp1 log-courier[26473]: Sending new payload of 128 events
Jan 15 15:02:01 smtp1 log-courier[26473]: Registrar received offsets for 128 log entries
Jan 15 15:02:01 smtp1 log-courier[26473]: Spooler flushing 128 events due to spool size reached
Jan 15 15:02:01 smtp1 log-courier[26473]: Send now open: Awaiting events for new payload
Jan 15 15:02:01 smtp1 log-courier[26473]: Sending new payload of 128 events
Jan 15 15:02:01 smtp1 log-courier[26473]: ACKN message received for payload cfc74318e95e003cece9ec983c7b4520 sequence 128
Jan 15 15:02:01 smtp1 log-courier[26473]: 3 payloads still pending, resetting timeout
Jan 15 15:02:01 smtp1 log-courier[26473]: Registrar received offsets for 128 log entries
Jan 15 15:02:01 smtp1 log-courier[26473]: ACKN message received for payload 4cab58a021a4d064bf7220508ecff8c5 sequence 128
Jan 15 15:02:01 smtp1 log-courier[26473]: 2 payloads still pending, resetting timeout
Jan 15 15:02:01 smtp1 log-courier[26473]: Send now open: Awaiting events for new payload
Jan 15 15:02:01 smtp1 log-courier[26473]: Sending new payload of 128 events
Jan 15 15:02:01 smtp1 log-courier[26473]: Registrar received offsets for 128 log entries
Jan 15 15:02:01 smtp1 log-courier[26473]: Spooler flushing 128 events due to spool size reached
Jan 15 15:02:01 smtp1 log-courier[26473]: Spooler flushing 128 events due to spool size reached
```

After that - silence...

Also, when it's stuck, lc-admin doesn't work too:
```
/usr/local/bin/lc-admin -connect="unix:/var/run/log-courier-admin.socket" status
Log Courier version 1.3.1.g1d79349 client

Attempting connection to unix:/var/run/log-courier-admin.socket...
Connected

Connection error: read unix /var/run/log-courier-admin.socket: i/o timeout
```

And strace of log-courier process shows something like this in a loop:

```
[pid 26477] <... futex resumed> )       = 0
[pid 26480] futex(0xc21011f8e8, FUTEX_WAKE, 1 <unfinished ...>
[pid 26477] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 26480] <... futex resumed> )       = 1
[pid 26485] <... futex resumed> )       = 0
[pid 26480] futex(0xba3838, FUTEX_WAIT, 0, {0, 183689} <unfinished ...>
[pid 26485] fstat(16,  <unfinished ...>
[pid 26477] <... select resumed> )      = 0 (Timeout)
[pid 26485] <... fstat resumed> {st_mode=S_IFREG|0640, st_size=3805, ...}) = 0
[pid 26477] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 26485] read(16,  <unfinished ...>
[pid 26480] <... futex resumed> )       = -1 ETIMEDOUT (Connection timed out)
[pid 26477] <... select resumed> )      = 0 (Timeout)
[pid 26485] <... read resumed> "", 16384) = 0
[pid 26480] futex(0xc21008c0e8, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 26477] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 26485] fstat(14, {st_mode=S_IFREG|0640, st_size=62657, ...}) = 0
[pid 26477] <... select resumed> )      = 0 (Timeout)
[pid 26485] read(14,  <unfinished ...>
[pid 26477] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 26485] <... read resumed> "", 16384) = 0
[pid 26485] futex(0xc21008c0e8, FUTEX_WAKE, 1 <unfinished ...>
[pid 26477] <... select resumed> )      = 0 (Timeout)
[pid 26485] <... futex resumed> )       = 1
[pid 26480] <... futex resumed> )       = 0
[pid 26485] futex(0xba3838, FUTEX_WAIT, 0, {0, 999512598} <unfinished ...>
[pid 26480] fstat(15,  <unfinished ...>
[pid 26477] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 26480] <... fstat resumed> {st_mode=S_IFREG|0640, st_size=103450, ...}) = 0
[pid 26477] <... select resumed> )      = 0 (Timeout)
[pid 26480] read(15, "", 16384)         = 0
[pid 26477] select(0, NULL, NULL, NULL, {0, 20} <unfinished ...>
[pid 26480] epoll_wait(4, {}, 128, 0)   = 0
[pid 26480] futex(0xc21008c0e8, FUTEX_WAIT, 0, NULL <unfinished ...>
[pid 26477] <... select resumed> )      = 0 (Timeout)
[pid 26477] futex(0xba3a38, FUTEX_WAIT, 0, NULL
```
Log Courier version 1.3.2.g9d76ee5

This is with zmq, but same happened when using tcp output. Let me know on what/how i can help debug this.

Thanks!

**Comment by driskell** [comment] 2015-01-15 15:19
Thanks. Just to confirm, does CPU jump high?
Also, I assume restarting log courier resumes it? (That is, there's no issue at Logstash side and it just reconnects fine)

**Comment by driskell** [comment] 2015-01-15 15:21
Can you capture stdout/stderr to a file when you start log-courier (if not already)

Then when it gets stuck send SIGQUIT to it and it should stack trace to stdout/stderr. (Command `kill -QUIT 12345` will do it, 12345 being PID of log-courier)

**Comment by driskell** [comment] 2015-01-15 15:22
Doing the SIGQUIT will stop it too by the way. But stops it with the stack trace so all good! Just need to make sure to get it captured.

**Comment by sysmonk** [comment] 2015-01-15 15:38
Did have to wait long:

```
SIGQUIT: quit
PC=0x42ca51

runtime.notetsleepg(0xba37e0, 0xffffffffffffffff)
        /usr/local/go/src/pkg/runtime/lock_futex.c:190 +0x46 fp=0x7f2d20967f48
runtime.signal_recv(0x0)
        /usr/local/go/src/pkg/runtime/sigqueue.goc:110 +0xe2 fp=0x7f2d20967f70
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e fp=0x7f2d20967fa0
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1394 fp=0x7f2d20967fa8
created by os/signal.initÂ·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 1 [select]:
main.(*LogCourier).Run(0xc210059660)
        /root/tmp/log-courier/src/log-courier/log-courier.go:108 +0x74c
main.main()
        /root/tmp/log-courier/src/log-courier/log-courier.go:43 +0x2b

goroutine 4 [syscall]:
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1394

goroutine 5 [semacquire]:
sync.runtime_Semacquire(0xc210059d0c)
        /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*Mutex).Lock(0xc210059d08)
        /usr/local/go/src/pkg/sync/mutex.go:66 +0xd6
log/syslog.(*Writer).writeAndRetry(0xc210059cc0, 0x7, 0xc2100ed4c0, 0x1b, 0x0, ...)
        /usr/local/go/src/pkg/log/syslog/syslog.go:253 +0x72
log/syslog.(*Writer).Debug(0xc210059cc0, 0xc2100ed4c0, 0x1b, 0x0, 0x0)
        /usr/local/go/src/pkg/log/syslog/syslog.go:246 +0x56
github.com/op/go-logging.(*SyslogBackend).Log(0xc210000700, 0x5, 0x4, 0xc2100db5a0, 0x6a4101, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/syslog.go:48 +0x1bf
github.com/op/go-logging.(*moduleLeveled).Log(0xc21007e140, 0x5, 0x3, 0xc2100db5a0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/level.go:112 +0xc5
github.com/op/go-logging.(*multiLogger).Log(0xc2100728e0, 0x5, 0x2, 0xc2100db480, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/multi.go:31 +0x11f
github.com/op/go-logging.(*Logger).log(0xc210069150, 0x5, 0x701c70, 0x1c, 0xc2107bd340, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:163 +0x178
github.com/op/go-logging.(*Logger).Debug(0xc210069150, 0x701c70, 0x1c, 0xc2107bd340, 0x1, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:220 +0x62
lc-lib/admin.(*Listener).Run(0xc210059d80)
        /root/tmp/log-courier/src/lc-lib/admin/listener.go:122 +0x4b4
created by lc-lib/core.(*Pipeline).Start
        /root/tmp/log-courier/src/lc-lib/core/pipeline.go:65 +0x69

goroutine 6 [IO wait]:
net.runtime_pollWait(0x7f2d20aec720, 0x77, 0x0)
        /usr/local/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc21007d5a0, 0x77, 0x7f2d20aeaf00, 0xb)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitWrite(0xc21007d5a0, 0xb, 0x7f2d20aeaf00)
        /usr/local/go/src/pkg/net/fd_poll_runtime.go:90 +0x30
net.(*netFD).Write(0xc21007d540, 0xc210061240, 0x56, 0xc0, 0x0, ...)
        /usr/local/go/src/pkg/net/fd_unix.go:297 +0x3e2
net.(*conn).Write(0xc2100006f8, 0xc210061240, 0x56, 0xc0, 0x6, ...)
        /usr/local/go/src/pkg/net/net.go:130 +0xc5
fmt.Fprintf(0x7f2d20aec8f0, 0xc2100006f8, 0x6eb4b0, 0x13, 0x7f2d1dc22b30, ...)
        /usr/local/go/src/pkg/fmt/print.go:221 +0xb0
log/syslog.(*netConn).writeString(0xc210072880, 0x7, 0xc210072800, 0x17, 0x6e0550, ...)
        /usr/local/go/src/pkg/log/syslog/syslog.go:294 +0x2a8
log/syslog.(*Writer).write(0xc210059cc0, 0x7, 0xc2107bab40, 0x2e, 0x446dc2, ...)
        /usr/local/go/src/pkg/log/syslog/syslog.go:276 +0x169
log/syslog.(*Writer).writeAndRetry(0xc210059cc0, 0x7, 0xc2107bab40, 0x2e, 0x0, ...)
        /usr/local/go/src/pkg/log/syslog/syslog.go:257 +0xd1
log/syslog.(*Writer).Debug(0xc210059cc0, 0xc2107bab40, 0x2e, 0x0, 0x0)
        /usr/local/go/src/pkg/log/syslog/syslog.go:246 +0x56
github.com/op/go-logging.(*SyslogBackend).Log(0xc210000700, 0x5, 0x4, 0xc21043d5a0, 0x6a4101, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/syslog.go:48 +0x1bf
github.com/op/go-logging.(*moduleLeveled).Log(0xc21007e140, 0x5, 0x3, 0xc21043d5a0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/level.go:112 +0xc5
github.com/op/go-logging.(*multiLogger).Log(0xc2100728e0, 0x5, 0x2, 0xc2104456c0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/multi.go:31 +0x11f
github.com/op/go-logging.(*Logger).log(0xc21000a960, 0x5, 0x71df70, 0x2d, 0xc2103cda50, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:163 +0x178
github.com/op/go-logging.(*Logger).Debug(0xc21000a960, 0x71df70, 0x2d, 0xc2103cda50, 0x1, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:220 +0x62
lc-lib/registrar.(*AckEvent).Process(0xc210112f00, 0xc2100852d0)
        /root/tmp/log-courier/src/lc-lib/registrar/event_ack.go:37 +0x249
lc-lib/registrar.(*Registrar).Run(0xc2100822d0)
        /root/tmp/log-courier/src/lc-lib/registrar/registrar.go:157 +0x12e
created by lc-lib/core.(*Pipeline).Start
        /root/tmp/log-courier/src/lc-lib/core/pipeline.go:65 +0x69

goroutine 7 [semacquire]:
sync.runtime_Semacquire(0xc210059d0c)
        /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*Mutex).Lock(0xc210059d08)
        /usr/local/go/src/pkg/sync/mutex.go:66 +0xd6
log/syslog.(*Writer).writeAndRetry(0xc210059cc0, 0x7, 0xc2108fb1e0, 0x2e, 0x0, ...)
        /usr/local/go/src/pkg/log/syslog/syslog.go:253 +0x72
log/syslog.(*Writer).Debug(0xc210059cc0, 0xc2108fb1e0, 0x2e, 0x0, 0x0)
        /usr/local/go/src/pkg/log/syslog/syslog.go:246 +0x56
github.com/op/go-logging.(*SyslogBackend).Log(0xc210000700, 0x5, 0x4, 0xc2108f92d0, 0x6a4101, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/syslog.go:48 +0x1bf
github.com/op/go-logging.(*moduleLeveled).Log(0xc21007e140, 0x5, 0x3, 0xc2108f92d0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/level.go:112 +0xc5
github.com/op/go-logging.(*multiLogger).Log(0xc2100728e0, 0x5, 0x2, 0xc2108f91b0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/multi.go:31 +0x11f
github.com/op/go-logging.(*Logger).log(0xc21000a9f0, 0x5, 0x71dfb0, 0x2e, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:163 +0x178
github.com/op/go-logging.(*Logger).Debug(0xc21000a9f0, 0x71dfb0, 0x2e, 0x0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:220 +0x62
lc-lib/publisher.(*Publisher).Run(0xc21005d2d0)
        /root/tmp/log-courier/src/lc-lib/publisher/publisher.go:268 +0xd23
created by lc-lib/core.(*Pipeline).Start
        /root/tmp/log-courier/src/lc-lib/core/pipeline.go:65 +0x69

goroutine 8 [semacquire]:
sync.runtime_Semacquire(0xc210059d0c)
        /usr/local/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*Mutex).Lock(0xc210059d08)
        /usr/local/go/src/pkg/sync/mutex.go:66 +0xd6
log/syslog.(*Writer).writeAndRetry(0xc210059cc0, 0x7, 0xc21007ee80, 0x35, 0x0, ...)
        /usr/local/go/src/pkg/log/syslog/syslog.go:253 +0x72
log/syslog.(*Writer).Debug(0xc210059cc0, 0xc21007ee80, 0x35, 0x0, 0x0)
        /usr/local/go/src/pkg/log/syslog/syslog.go:246 +0x56
github.com/op/go-logging.(*SyslogBackend).Log(0xc210000700, 0x5, 0x4, 0xc2108f9900, 0x6a4101, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/syslog.go:48 +0x1bf
github.com/op/go-logging.(*moduleLeveled).Log(0xc21007e140, 0x5, 0x3, 0xc2108f9900, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/level.go:112 +0xc5
github.com/op/go-logging.(*multiLogger).Log(0xc2100728e0, 0x5, 0x2, 0xc2108f97e0, 0x0, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/multi.go:31 +0x11f
github.com/op/go-logging.(*Logger).log(0xc21000aa20, 0x5, 0x726950, 0x34, 0xc2107bdd50, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:163 +0x178
github.com/op/go-logging.(*Logger).Debug(0xc21000aa20, 0x726950, 0x34, 0xc2107bdd50, 0x1, ...)
        /root/tmp/log-courier/src/github.com/op/go-logging/logger.go:220 +0x62
lc-lib/spooler.(*Spooler).Run(0xc21007d9a0)
        /root/tmp/log-courier/src/lc-lib/spooler/spooler.go:95 +0x545
created by lc-lib/core.(*Pipeline).Start
        /root/tmp/log-courier/src/lc-lib/core/pipeline.go:65 +0x69

goroutine 9 [select]:
lc-lib/prospector.(*Prospector).Run(0xc210060b00)
        /root/tmp/log-courier/src/lc-lib/prospector/prospector.go:181 +0xb91
created by lc-lib/core.(*Pipeline).Start
        /root/tmp/log-courier/src/lc-lib/core/pipeline.go:65 +0x69

goroutine 11 [select]:
lc-lib/harvester.(*Harvester).eventCallback(0xc210064ea0, 0x147ba58df, 0x147ba59e2, 0xc2108dd900, 0x102)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:296 +0x6ff
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)Â·fm(0x147ba58df, 0x147ba59e2, 0xc2108dd900, 0x102)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecFilter).Event(0xc210085420, 0x147ba58df, 0x147ba59e2, 0xc2108dd900, 0x102)
        /root/tmp/log-courier/src/lc-lib/codecs/filter.go:87 +0xdd
lc-lib/harvester.(*Harvester).harvest(0xc210064ea0, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:179 +0x6d1
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 12 [select]:
lc-lib/harvester.(*Harvester).eventCallback(0xc210064000, 0x85a87e, 0x85a8c3, 0xc210082b90, 0x44)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:296 +0x6ff
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)Â·fm(0x85a87e, 0x85a8c3, 0xc210082b90, 0x44)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc21007f6a0, 0x85a87e, 0x85a8c3, 0xc210082b90, 0x44)
        /root/tmp/log-courier/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc210064000, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:179 +0x6d1
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 13 [select]:
lc-lib/harvester.(*Harvester).readline(0xc2100640d0, 0xc2100b0900, 0xba38e0, 0x10e42b96b5, 0x0, ...)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:368 +0x318
lc-lib/harvester.(*Harvester).harvest(0xc2100640d0, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:148 +0x2da
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 14 [select]:
lc-lib/harvester.(*Harvester).readline(0xc210064270, 0xc2100b0980, 0xba38e0, 0x10e42b40e4, 0x0, ...)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:368 +0x318
lc-lib/harvester.(*Harvester).harvest(0xc210064270, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:148 +0x2da
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 15 [select]:
lc-lib/harvester.(*Harvester).readline(0xc2100370d0, 0xc2100b0a00, 0xba38e0, 0x10e42a89fb, 0x0, ...)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:368 +0x318
lc-lib/harvester.(*Harvester).harvest(0xc2100370d0, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:148 +0x2da
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 16 [select]:
lc-lib/harvester.(*Harvester).readline(0xc2100371a0, 0xc2100b0a80, 0xba38e0, 0xe7a3656b2, 0x0, ...)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:368 +0x318
lc-lib/harvester.(*Harvester).harvest(0xc2100371a0, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:148 +0x2da
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 17 [select]:
lc-lib/harvester.(*Harvester).eventCallback(0xc210037270, 0x52836c, 0x528467, 0xc21005ea00, 0xfa)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:296 +0x6ff
lc-lib/harvester.*Harvester.(lc-lib/harvester.eventCallback)Â·fm(0x52836c, 0x528467, 0xc21005ea00, 0xfa)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:84 +0x4e
lc-lib/codecs.(*CodecPlain).Event(0xc21007fb70, 0x52836c, 0x528467, 0xc21005ea00, 0xfa)
        /root/tmp/log-courier/src/lc-lib/codecs/plain.go:52 +0x51
lc-lib/harvester.(*Harvester).harvest(0xc210037270, 0xc21003c7e0, 0x0, 0x0, 0x0)
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:179 +0x6d1
lc-lib/harvester.funcÂ·001()
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:92 +0x72
created by lc-lib/harvester.(*Harvester).Start
        /root/tmp/log-courier/src/lc-lib/harvester/harvester.go:94 +0x8b

goroutine 18 [select]:
lc-lib/transports.(*TransportZmq).bridge(0xc21003c700, 0xc2100ae430)
        /root/tmp/log-courier/src/lc-lib/transports/zmq.go:389 +0x396
created by lc-lib/transports.(*TransportZmq).Init
        /root/tmp/log-courier/src/lc-lib/transports/zmq.go:349 +0x1892

goroutine 19 [syscall]:
github.com/alecthomas/gozmq._C2func_zmq_poll(0xc2108fba50, 0x3, 0xffffffffffffffff, 0xc2108fba50, 0x3, ...)
        github.com/alecthomas/gozmq/_obj/_cgo_defun.c:315 +0x31
github.com/alecthomas/gozmq.Poll(0xc21010b1e0, 0x3, 0x3, 0xffffffffffffffff, 0x1, ...)
        /root/tmp/log-courier/src/github.com/alecthomas/gozmq/zmq.go:428 +0x197
lc-lib/transports.(*TransportZmq).poller(0xc21003c700, 0xc2100ae440)
        /root/tmp/log-courier/src/lc-lib/transports/zmq.go:435 +0x14f
created by lc-lib/transports.(*TransportZmq).Init
        /root/tmp/log-courier/src/lc-lib/transports/zmq.go:352 +0x18b9

rax     0xca
rbx     0xc2100280e8
rcx     0xffffffffffffffff
rdx     0x0
rdi     0xba37e0
rsi     0x0
rbp     0xc21000e000
rsp     0x7f2d20967eb0
r8      0x0
r9      0x0
r10     0x0
r11     0x286
r12     0x0
r13     0x1
r14     0x24
r15     0x10
rip     0x42ca51
rflags  0x286
cs      0x33
fs      0x0
gs      0x0
```

**Comment by sysmonk** [comment] 2015-01-15 15:49
Missed this comment:
```Thanks. Just to confirm, does CPU jump high?
Also, I assume restarting log courier resumes it? (That is, there's no issue at Logstash side and it just reconnects fine)```

No, i don't remember the CPU going up during the log-courier stuckiness.
And yes, it does resume after restarting log-courier. I have  monit check to restart log-courier if the state file doesn't change for 3 minutes, which helps me in this kind of situations :)

**Comment by driskell** [comment] 2015-01-15 16:44
Ok the blocking is occurring during syslog write. Syslog may be broken. Though from research on this in forwarder there's a known issue with golang and syslog which can cause blocking.

I'll have a look at ways around it and if any new research done on golang side. But disabling syslog output and logging to file instead will work around the problem.

**Comment by sysmonk** [comment] 2015-01-15 17:50
I'll try disabling syslog output and use only file to see if any more hangs occur, but generally syslog doesn't seem broken - everything else works writing to syslog. Thanks for researching

**Comment by sysmonk** [comment] 2015-01-16 08:53
So far it did not get stuck - sounds good. But i still prefer syslog output :(

**Comment by driskell** [comment] 2015-01-19 23:08
FYI - The golang issue moved here: https://github.com/golang/go/issues/5932
I've asked if there's any news on it. It does look highly kernel/machine specific though, and a very rare occurrence.

I've seen others hit the issue with Logstash Forwarder too on the mailing list and on GitHub Issues, e.g.:
https://github.com/elasticsearch/logstash-forwarder/issues/280
Hopefully we can get some movement.

Could you provide your kernel version and OS distribution and version? If I've got something similar I can try to reproduce and provide them some more info/diagnostics.

**Comment by sysmonk** [comment] 2015-01-20 08:41
We mainly use Debian, and i have the same issue on a number of different versions of debian: 71, 7.5, 7.6
The 7.1 might be happening less often than on 7.5/7.6, or maybe just a coincidence.

**Comment by sysmonk** [comment] 2015-01-20 08:48
The amount of logs is around the same-ish, but the 7.1 got restarted less often. In example for yesterday:

```
# cat /etc/debian_version ; zgrep -c 'Pipeline ready' /var/log/log-courier.log.1.gz; xzcat /var/log/mail.log.1.xz | wc -l
7.6
217
101673762
```
and
```
# cat /etc/debian_version ; zgrep -c 'Pipeline ready' /var/log/log-courier.log.1.gz; xzcat /var/log/mail.log.1.xz | wc -l
7.1
133
101368251
```
The amount of logs is around the same-ish

**Comment by driskell** [comment] 2015-01-20 08:50
Can you grab output of uname -a to grab kernel version?

**Comment by sysmonk** [comment] 2015-01-20 09:45
They are all on different versions of kernel:
Linux smtp1 3.12-0.bpo.1-amd64 #1 SMP Debian 3.12.9-1~bpo70+1 (2014-02-07) x86_64 GNU/Linux
Linux smtp2 3.10-0.bpo.2-amd64 #1 SMP Debian 3.10.5-1~bpo70+1 (2013-08-11) x86_64 GNU/Linux
Linux smtp3 3.16-0.bpo.2-amd64 #1 SMP Debian 3.16.3-2~bpo70+1 (2014-09-21) x86_64 GNU/Linux

**Comment by driskell** [comment] 2015-02-28 14:48
I've not been able to find a fix for this. Appears to be related to Go std library. Will try to find some time after 1.5 release to look into more detail but being unable to reproduce makes it difficult. Will mark help wanted in case anyone else finds a reproduction case and is able to help fix the Go std library or wherever the issue lies.

**Comment by driskell** [comment] 2015-08-07 10:05
Not seen this reported in a while so will close it. Can reopen if it pops back up. I've not checked the golang-nuts archives to see if was any update but could be resolved now.

**Closed by driskell** 2015-08-07 10:05 UTC
Labels: bug, help wanted
