### ISSUE TITLE
Installation of the Logstash-Plugin on Logstash branch 1.5

### ISSUE THREAD

**Issue by hinnerk** [driskell/log-courier#121] opened 2015-02-23 18:05 UTC
The installation of the Logstash-Plugin on the current branch 1.5 appears not to work any more:

```
$ /opt/logstash/bin/plugin install logstash-input-log-courier
Validating logstash-input-log-courier
Installing logstash-input-log-courier
Plugin version conflict, aborting
Installation aborted
```

**Comment by driskell** [comment] 2015-02-23 18:15
Just to confirm. Is this a fresh install of Logstash that never had courier installed before? Just want to rule out any upgrading of the courier plugin.

**Comment by hinnerk** [comment] 2015-02-23 19:08
Yes, it's a freshly built docker image.

**Comment by driskell** [comment] 2015-02-25 12:50
Are there any other plugins installed or is this the first plugin installed? Just need to check if it's a conflict with an existing plugin or not. Thanks.

**Comment by hinnerk** [comment] 2015-02-25 15:10
After installation from the branch 1.5 I do:

1. `/opt/logstash/bin/plugin update`
2. `/opt/logstash/bin/plugin install logstash-filter-translate`
3. `/opt/logstash/bin/plugin install logstash-output-riemann`
4. `/opt/logstash/bin/plugin install logstash-input-log-courier`

**Comment by driskell** [comment] 2015-02-28 10:35
With beta1 it works OK.

I can see in beta2 there are some breaking changes to the plugin system. I'll fix these in develop. You'll need to manually build the gems and install them though as I won't be pushing new ones to RubyGems until next release. I'll also note in the docs that 1.5 is still WIP and subject to breakages until the API stabilises.

**Comment by jmreicha** [comment] 2015-03-06 22:18
+1

Experiencing this issue with Logstash 1.5.0.rc2

**Comment by mitchcapper** [comment] 2015-03-08 21:15
+1 for rc-2 or rc-1 from the primary channel, downgrading to 1.5.0.beta1-1 fixes the issue.

**Comment by driskell** [comment] 2015-03-08 21:29
There's a PR to fix this.

I've been reluctant to merge just yet in case things change again. With the RC release I think it may be safe now so I'll get this merged soon once I've tested with RC2 (I tested 1.5 branch shortly before the RC but need to confirm)

**Comment by ryan-stateless** [comment] 2015-03-10 16:22
+1

**Comment by matejzero** [comment] 2015-03-11 06:04
I would like to try 1.5.0RC2 on our test env as well, so I'm waiting for this fix...

**Comment by mareklobaza** [comment] 2015-03-12 07:12
1+
Experiencing problem too with 1.5.0RC2
Work with beta1-1

**Comment by nopslip** [comment] 2015-03-18 22:20
+1

**Comment by ruddj** [comment] 2015-03-19 04:46
+1. I was unable to use with 1.50RC2 and was unable to compile the new .gemspec as I get "Invalid gemspec in [logstash-input-log-courier.gemspec]: undefined method `metadata=" caused by having a too old version of Gem in Ubuntu 14.04

**Comment by driskell** [comment] 2015-03-22 00:44
For record, this is the conflict reason:
LogStash::PluginManager::Error: Installation aborted: Could not find gem 'logstash (~> 1.4) java', which is required by gem 'logstash-input-log-courier (>= 0) java', in any of the sources.

elastic/logstash#2677 there was some breaking changes and all their plugins updated. Just testing at the moment on older betas and will merge this and publish a new gem version in the near future.

**Comment by driskell** [comment] 2015-03-22 00:48
After this merge, installations on beta1 will not work, only RC1 and RC2 will work. This should be fine.
The error one would get on beta is:
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: logstash-input-log-courier (= 1.3) requires logstash-core (~> 1.4)

**Comment by mareklobaza** [comment] 2015-03-22 18:55
Problem still exists on 1.5 RC1 and RC2. I can confirm it doesn't work with beta1 so for this moment we have no working version of logstash 1.5 for provisioning.
Please revert your changes!

Logstash error:
Plugin version conflict, aborting
LogStash::PluginManager::Error: Installation aborted
     execute at /opt/logstash/lib/logstash/pluginmanager/install.rb:93
...

**Comment by driskell** [comment] 2015-03-22 19:51
Let me test - sorry about this. I did test it. I've discard everything and starting again and testing again just in case.

**Comment by driskell** [comment] 2015-03-22 19:59
OK - I think I was testing with a stock Logstash with minimal plugins. Now I've rebuilt it's got a lot more plugins (all the standard ones) and that's where the conflict is happening this time. Previously, the conflict was caused by a rename of the "Logstash" dependency from "logstash" to "logstash-core".

This time it's due to the logstash-output-zeromq (and probably logstash-input-zeromq too) restricting their ffi-rzmq gem dependency.

Error: Bundler::VersionConflict, Bundler could not find compatible versions for gem "ffi-rzmq":
  In Gemfile:
    logstash-input-log-courier (>= 0) java depends on
      log-courier (= 1.6) java depends on
        ffi-rzmq (~> 2.0) java

    logstash-output-zeromq (>= 0) java depends on
      ffi-rzmq (1.0.0)

This is problematic because we need ffi-rzmq for CurveZMQ. I will need to try obtain a fix upstream.

**Comment by driskell** [comment] 2015-03-22 20:01
I think actually this may have been the case always (even in beta1/beta2) if the zeromq plugin was installed. Which potentially those betas had less plugins available by default.

For 1.4 it pretty much forces an upgrade so was never a problem.

**Comment by driskell** [comment] 2015-03-22 20:16
I've posted in elastic/logstash-output-zeromq#1 - It'll be great if people could request the dependency upgrade there too.

**Comment by mareklobaza** [comment] 2015-03-24 18:32
I'm just wondering - you mentined that you had test logstsh-input-log-courier plugin very first time on the fresh instalation of logstash (RC2, git?) with minimal plugins and it was working for you?
So is there any conditions that allow mi to install this plugin by the logstash's plugin manager?
For this moment I'm unable to do that for all version of logstash 1.5.*

**Comment by driskell** [comment] 2015-03-24 18:42
Removing logstash-output-zeromq and then running an update of logstash-input-zeromq should make it possible to install the plugin.

You just won't have the default zeromq output plugin anymore.

I'm raising the PR tonight for this hopefully.

**Comment by iemem15** [comment] 2015-03-24 20:49
problem with ganglia
Installing logstash-input-ganglia
Error Bundler::InstallError, retrying 1/10

**Comment by driskell** [comment] 2015-03-24 21:13
@iemem15 This is wrong place for issues with that plugin. A good top though, run like this for more info: "DEBUG=1 bin/plugin install logstash-input-ganglia". Please don't respond here, I would like to keep the topic clear. Thanks!

**Comment by mareklobaza** [comment] 2015-03-24 23:32
Hurray, logstash-input-log-courier is working with logstash 1.5.* again, after update of logstash-output-zeromq to 0.1.5.
Remember to call:
bin/plugin update logstash-output-zeromq for logstash 1.5RC2 before install log-courier input plugin!

**Comment by ruddj** [comment] 2015-03-24 23:46
Do we also need to call 'bin/plugin update logstash-input-zeromq' to update that as well or it doesn't matter as default install doesn't specify version?

**Comment by nopslip** [comment] 2015-03-24 23:58
Thanks @driskell :+1:

**Comment by jmreicha** [comment] 2015-03-25 00:20
@ruddj I had to update the `logstash-input-zeromq` first.

**Comment by ruddj** [comment] 2015-03-25 01:40
Thanks @jmreicha .

**Comment by driskell** [comment] 2015-03-31 08:04
Good to hear it's solved!

Steps to install the courier input on 1.5 RC1 will now be:

1. `bin/plugin update logstash-output-zeromq`
2. `bin/plugin install logstash-input-log-courier`

Just to be up to date it's best to also run:

* `bin/plugin update logstash-input-zeromq`

**Closed** 2015-03-31 08:07 UTC
Labels: bug, roadmap
