### ISSUE TITLE
"worker" thread throw UnsupportedOperationException without log report

### ISSUE THREAD

**Issue by mareklobaza** [driskell/log-courier#155] opened 2015-04-24 14:37 UTC
Times to times logstash hangs doing nothing even CPU consumption is high. Problem seems to be connected with log-courer input plugin.

Configurations:
1. Logstash 1.5.0-RC2.
2. Log-courier input plugin (1.6)
3.  
```
"general": {
    "admin enabled": true,
    "admin listen address": "tcp:127.0.0.1:1234",
    "log level": "debug",
    "log file": "/u01/log-courier-logs/log-courier.log"
  },
  "network": {
    "transport": "plainzmq",
    "servers": ["xxx.xxx.xxx.xxx:5509"]
  },
  "files": [
    {
...
```

Symptoms:
Log-courier all the time producing the same `ACKN message received for payload` for the same message and sequence number. E.g.:
```
2015/04/24 13:21:53.887078 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:21:53.887151 2 payloads still pending, resetting timeout
2015/04/24 13:21:58.876775 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:21:58.876837 2 payloads still pending, resetting timeout
2015/04/24 13:22:03.903230 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:22:03.903293 2 payloads still pending, resetting timeout
2015/04/24 13:22:08.893441 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:22:08.893518 2 payloads still pending, resetting timeout
2015/04/24 13:22:13.899078 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:22:13.899157 2 payloads still pending, resetting timeout
2015/04/24 13:22:18.897287 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:22:18.897350 2 payloads still pending, resetting timeout
2015/04/24 13:22:23.904764 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13
2015/04/24 13:22:23.904833 2 payloads still pending, resetting timeout
2015/04/24 13:22:28.907031 ACKN message received for payload 41472f2199c3d4e7652c66272ed81a9b sequence 13

```
Nothing in logstash's log (only Partially acknowledging message):
```
{:timestamp=>"2015-04-24T13:21:12.510000+0200", :message=>"filters/LogStash::Filters::Xml: adding tag", :tag=>"xml_parsed", :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"187", :method=>"filter_matched", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:18.848000+0200", :message=>"Idle source shutting down", :source=>"006b8b4568", :level=>:info, :file=>"log-courier/server_zmq.rb", :line=>"314", :method=>"try_drop", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:35.757000+0200", :message=>"Idle source shutting down", :source=>"006b8b4567", :level=>:info, :file=>"log-courier/server_zmq.rb", :line=>"314", :method=>"try_drop", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:38.841000+0200", :message=>"New source", :source=>"006b8b4568", :level=>:info, :file=>"log-courier/server_zmq.rb", :line=>"257", :method=>"deliver", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:40.594000+0200", :message=>"New source", :source=>"006b8b4567", :level=>:info, :file=>"log-courier/server_zmq.rb", :line=>"257", :method=>"deliver", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:43.866000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:48.867000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:53.867000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:58.869000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:21:58.869000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:03.872000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:03.872000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:08.879000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:08.880000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:13.883000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:13.883000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:18.892000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:23.895000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:23.896000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:28.899000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:28.900000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:33.903000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:33.904000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:38.905000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:43.907000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:43.907000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:48.910000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:53.911000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:53.911000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:58.914000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:22:58.914000+0200", :message=>"Partially acknowledging message", :nonce=>"41472f2199c3d4e7652c66272ed81a9b", :sequence=>13, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
{:timestamp=>"2015-04-24T13:23:03.917000+0200", :message=>"Partially acknowledging message", :nonce=>"1e1d4fa553f6ec3d904f7344d5474d74", :sequence=>0, :level=>:debug, :file=>"log-courier/server.rb", :line=>"193", :method=>"process_jdat", "plugin"=>"input/courier", "port"=>5509}
...
```
but there's exceptions produced on console:
```
Apr 24, 2015 1:20:16 PM org.elasticsearch.discovery.DiscoveryService doStart
INFO: [logstash-servername-17029-14950] DefaultCluster/mqC681fbSUCGe68J2QfzhQ
Apr 24, 2015 1:20:19 PM org.elasticsearch.cluster.service.InternalClusterService$UpdateTask run
INFO: [logstash-servername-17029-14950] detected_master (...)
Apr 24, 2015 1:20:19 PM org.elasticsearch.node.internal.InternalNode start
INFO: [logstash-servername-17029-14950] started
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```
Happens randomly (sometimes 2-3 days everthing is fine, sometimes happpens in 5-6 minutes after restart). Only logstash's restart helps, but first log-courier has to be stopped - seems log-courier held some resorces!

If I restart logstash without stopping log-courier exception will be thrown imediatelly:
```
INFO: [logstash-servername-17029-14950] DefaultCluster/T9XNM033RH6xAcZf8yvt2A
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Apr 24, 2015 1:18:23 PM org.elasticsearch.cluster.service.InternalClusterService$UpdateTask run
INFO: [logstash-servername-17029-14950] detected_master (...)
Apr 24, 2015 1:18:23 PM org.elasticsearch.node.internal.InternalNode start
INFO: [logstash-servername-17029-14950] started
```
gives misleading view that everything is fine! 
Experiencing this for few months also with previous version of logstash.

**Comment by driskell** [comment] 2015-04-24 14:59
If you are not using multiple servers in the log-courier config - can you try the tcp transport instead?
When using single server, tcp is preferred. In fact zmq will be obsoleted and removed in version 2.0.

**Comment by driskell** [comment] 2015-04-24 14:59
This will rule out any issue with the zmq libraries and related code etc, and narrow thing things down.

**Comment by mareklobaza** [comment] 2015-04-27 07:06
We're using single server for this moment but need the scalability which gives zeromq. Of cource I'll setup configuration for TCP to check whether the problem lies with zeromq or not.

I saw already few issues maybe connected with `ACKN message received for payload` in loop and need to know is there other users experience similar problem or rather problem is only for our side.

Also can you give some short view of version 2.0 and remove zeromq? How will be multiple servers handled? Is there any deadline of 2.0?

**Comment by driskell** [comment] 2015-04-27 12:54
@mareklobaza I've put reasoning behind removing ZeroMQ here: https://github.com/driskell/log-courier/blob/develop/docs/ZeroMQSupport.md

I'll expand on it soon. But essentially ZeroMQ is hiding queues and server status from us so we cannot act accordingly, and it means if ANY breakage occurs on any server it can have bad impact on performance. And the library I'm using has gone maintenance only.

So rather than battle with hidden systems in ZeroMQ and have to rewrite the transport for a different and currently maintained library, I'm making the TCP and TLS transports connect to multiple servers. So there should be no loss in behaviour. In fact there should be a improvement in reliability when failures occur, and provide more features (such as a failover/failback mode - currently it's only failover only and does not failback)

**Comment by driskell** [comment] 2015-04-27 12:55
`ACKN message received for payload` should not be looping. Though if the pipeline in Logstash does not move it will continue to periodically resend the same acknowledgement. This acts as a keep alive to stop the connection dropping. (Log Courier will disconnect if Logstash doesn't send anything in a 15 second time period so something has to be sent periodically to stop a timeout - see `timeout` in `network` config.)

**Comment by mareklobaza** [comment] 2015-04-28 09:23
Yep, that's true. As was mentioned only worker thread is down (without signal), so the rest logstash's threads are working and keeping connection with log-courier (wating for event_queue), that's why timeout is refreshing for log-courier side. 
The question is why the working thread die sometimes - does the problem lie with log-courier, logstash or zeromq?
I'd say that logstash should alarm about such situations and shut down/restart (or maybe it tries but zeromq hide failure reason internally as you experienced already).
Another question is why the log-courier has to be stopped before logstash restart? It's queue so it shouldn't be any strong coupling between!
We're experiencing this time to time at least on 5 separate installations!

**Comment by driskell** [comment] 2015-04-28 09:54
I've had this referred to in elastic/logstash-forwarder#438

Can you try `--debug` option on Logstash running from command line? It'll help work out why worker thread is dying. I suggested that in above issue.

**Comment by mareklobaza** [comment] 2015-04-28 11:40
That's exactly the problem - logstash's log is empty about the issue occured, even in debug mode (see quoted logs - logstash has been run with `--debug` flag: `:level=>:debug `

**Comment by driskell** [comment] 2015-04-28 12:35
@mareklobaza Could you provide Logstash filter config so we can check it? Maybe it's a similar issue to the 438 I mentioned, where a filter was causing the worker to stop.

**Comment by driskell** [comment] 2015-04-30 08:31
@mareklobaza I can confirm if you run Logstash from command line, and with --debug, it will tell you the reason the filter is dying. It looks like if you run as service it will buffer logs, and since logs stop pretty much once the error occurs, the error gets trapped in a buffer. Of course, killing the service means the buffer never gets flushed.

So try running from command line like this:

`./bin/logstash --debug -f /path/to/logstash.conf`

**Comment by driskell** [comment] 2015-05-12 15:11
I will close this as it's gone quiet. If you have issues still let me know if the `--debug` works better when running from the command line. Generally this is an issue within Logstash, either with filters, or with the courier input plugin. In this instance it is the filters.

**Closed by driskell** 2015-05-12 15:11 UTC

**Comment by mareklobaza** [comment] 2015-05-13 07:12
Yep, you can closed it. You gaved me right direction but poining of maybe wrong grok configuration. I figured out that we're parsing value as quoted string which for some rare situations can be simple dash sign, which seems trigger logstash to crash without throw _grokparsefailure exception. 
As I said it happens time to time so still waiting when crash again but for sure will ask elastic team for help with it.
