### ISSUE TITLE
log-courier won't connect with logstash after logstash has run a long time

### ISSUE THREAD

**Issue by arep** [driskell/log-courier#104] opened 2015-01-31 22:29 UTC
I run log-courier on around 20 servers, and they all connect directly to my logstash server via TLS  and the log-courier plugin. Works very well for now.
But some time, very seldom, one server crashes. When I reboot it log-courier won't connect to logstash anymore. (logstash has been running for a while when this happens, and I'm not sure how long)

Syslog for log-courier has this:
Transport init failed: TLS Handshake failure with aaa.bbb.ccc.ddd: read tcp aaa.bbb.ccc.ddd:5043: i/o timeout

When I restart logstash, it connects, and all the other servers also reconnect and everything is good.

Any idea what this is?

(next time I'll try to remember to check if other servers also can't connect to logstash if I restart log-courier on them)

**Comment by driskell** [comment] 2015-02-02 22:42
Can you confirm your Log Courier version? I know in 1.3 there was a fix for this error - the cause was a single client that timed out during handshake could prevent other clients from successfully connecting.

**Comment by arep** [comment] 2015-02-03 09:55
ok, I'll try to upgrade. I seem to run version 0.15

**Comment by driskell** [comment] 2015-02-03 21:45
Thanks - if you're still having issues with 1.3, feel free to reopen the issue. But I believe it should solve it for you as there is a fix specifically for this problem in there.

**Closed by driskell** 2015-02-03 21:45 UTC
