### ISSUE TITLE
TLS Handshake Failure

### ISSUE THREAD

**Issue by Rajeshkumar123** [driskell/log-courier#170] opened 2015-05-29 06:55 UTC
I am gettign the below error when I tried to fetch the files using log courier.

2015/05/28 23:42:10.522691 Attempting to connect to 127.0.0.1:10544
2015/05/28 23:42:11.529463 Transport init failed: Failed to connect to 127.0.0.1
:10544: dial tcp 127.0.0.1:10544: ConnectEx tcp: No connection could be made bec
ause the target machine actively refused it.
2015/05/28 23:42:12.532328 Attempting to connect to 127.0.0.1:10544
2015/05/28 23:42:13.621126 Transport init failed: Failed to connect to 127.0.0.1
:10544: dial tcp 127.0.0.1:10544: ConnectEx tcp: No connection could be made bec
ause the target machine actively refused it.
2015/05/28 23:42:14.623991 Attempting to connect to 127.0.0.1:10544
2015/05/28 23:42:15.628810 Transport init failed: Failed to connect to 127.0.0.1
:10544: dial tcp 127.0.0.1:10544: ConnectEx tcp: No connection could be made bec
ause the target machine actively refused it.
2015/05/28 23:42:16.631675 Attempting to connect to 127.0.0.1:10544
2015/05/28 23:42:17.720473 Transport init failed: Failed to connect to 127.0.0.1
:10544: dial tcp 127.0.0.1:10544: ConnectEx tcp: No connection could be made bec
ause the target machine actively refused it.

Below is my logcourier conf file

{
	"general": {
		"log level" : "debug",
		"persist directory" : "C:/Ja/setup/log"
	},

	"network": {
		"servers": [ "127.0.0.1:10544" ],
		"ssl ca": "C:/Ja/setup/selfsigned.crt"
	},
	"files": [
	{
			"paths": [ 
				  "C:/Java1/setup/log/logs/*.log"
			],
			"fields": { "type": "w3c_err" },
			"dead time": "3000s"
		}
		
	]
}

Below is my logstash conf file

input {
   courier {
		port => 10544 
		ssl_certificate => "C:/Java1/setup/selfsigned.crt"
		ssl_key         => "C:/Java1/setup/selfsigned.key"

	}
}

**Comment by driskell** [comment] 2015-05-29 07:19
Duplicate of #169

**Closed by driskell** 2015-05-29 07:19 UTC
